from __future__ import annotations

import json
import tempfile
import unittest
from subprocess import CompletedProcess
from pathlib import Path
from unittest.mock import patch

from config.persistence import PersistentStoreError
from dns.resolver_inventory import ResolverManager
from dns.state_manager import (
    DNSStateError,
    LocalDNSEntryPoint,
    SystemDNSStateManager,
    _run_command,
    _replace_symlink,
    default_snapshot_path,
    load_snapshot,
)


class FakeRunner:
    def __init__(
        self,
        active_services: set[str] | None = None,
        active_connections: tuple[str, ...] = (),
        connection_values: dict[str, tuple[str, str, str, str, str, str]] | None = None,
        fail_on: tuple[str, ...] = (),
    ) -> None:
        self.active_services = active_services or set()
        self.active_connections = active_connections
        self.connection_values = connection_values or {}
        self.fail_on = fail_on
        self.commands: list[list[str]] = []

    def __call__(self, command: list[str]) -> str:
        self.commands.append(command)
        joined = " ".join(command)
        if any(token in joined for token in self.fail_on):
            raise DNSStateError(f"forced failure: {joined}")
        if command[:2] == ["systemctl", "is-active"] and len(command) == 3:
            return "active" if command[2] in self.active_services else "inactive"
        if command == ["nmcli", "-t", "-f", "NAME", "con", "show", "--active"]:
            return "\n".join(self.active_connections)
        if command == ["nmcli", "-t", "-f", "NAME,TYPE,DEVICE", "con", "show", "--active"]:
            rendered = []
            for name in self.active_connections:
                if ":" in name:
                    rendered.append(name)
                else:
                    rendered.append(f"{name}:802-3-ethernet:eth0")
            return "\n".join(rendered)
        if command[:2] == ["nmcli", "-g"] and command[-2:] != ["show", "--active"]:
            # One property per call (dns/state_manager.py:
            # _nmcli_connection_property), not the old single comma-joined
            # -g query for all six at once - matches production exactly so
            # this mock cannot hide the real blank-line/strip() ordering bug
            # that query shape had.
            prop = command[2]
            name = command[-1]
            values = self.connection_values.get(name, ("", "no", "", "", "no", ""))
            index = {
                "connection.uuid": None,
                "ipv4.dns": 0,
                "ipv4.ignore-auto-dns": 1,
                "ipv4.dns-search": 2,
                "ipv6.dns": 3,
                "ipv6.ignore-auto-dns": 4,
                "ipv6.dns-search": 5,
            }[prop]
            if index is None:
                return "11111111-1111-1111-1111-111111111111"
            return values[index]
        return ""


class DNSStateManagerTests(unittest.TestCase):
    def test_networkmanager_snapshot_excludes_product_owned_tun_connections(self) -> None:
        with tempfile.TemporaryDirectory() as tmp:
            resolv_conf = Path(tmp) / "resolv.conf"
            resolv_conf.write_text(
                "# Generated by NetworkManager\nnameserver 192.0.2.53\n",
                encoding="utf-8",
            )
            runner = FakeRunner(
                active_services={"NetworkManager.service"},
                active_connections=(
                    "Wired connection 1:802-3-ethernet:eth0",
                    "wdvpn-tun0:tun:wdvpn-tun0",
                    "watchdogvpn_awg:tun:watchdogvpn_awg",
                ),
            )
            manager = SystemDNSStateManager(resolv_conf_path=resolv_conf, runner=runner)

            snapshot = manager.save_state()

        self.assertEqual(
            [connection.name for connection in snapshot.network_manager_connections],
            ["Wired connection 1"],
        )
        property_targets = [
            command[-1]
            for command in runner.commands
            if command[:2] == ["nmcli", "-g"]
        ]
        self.assertNotIn("wdvpn-tun0", property_targets)
        self.assertNotIn("watchdogvpn_awg", property_targets)

    def test_symlink_replace_reports_directory_durability_failure(self) -> None:
        with tempfile.TemporaryDirectory() as tmp:
            root = Path(tmp)
            target = root / "target"
            target.write_text("nameserver 127.0.0.1\n", encoding="utf-8")
            path = root / "resolv.conf"
            path.symlink_to(root / "old-target")

            with patch(
                "dns.state_manager.fsync_parent_directory",
                side_effect=PersistentStoreError("durability is not confirmed"),
            ):
                with self.assertRaisesRegex(DNSStateError, "durability"):
                    _replace_symlink(path, target)

            self.assertEqual(path.resolve(), target.resolve())

    def test_save_state_detects_systemd_resolved_and_apply_restore_link(self) -> None:
        with tempfile.TemporaryDirectory() as tmp:
            resolv_conf = Path(tmp) / "resolv.conf"
            resolv_conf.write_text("nameserver 127.0.0.53\n", encoding="utf-8")
            runner = FakeRunner(active_services={"systemd-resolved.service"})
            manager = SystemDNSStateManager(resolv_conf_path=resolv_conf, runner=runner)

            snapshot = manager.apply_local_dns(
                LocalDNSEntryPoint(address="127.0.0.1", systemd_link="tun0")
            )
            manager.restore_state(snapshot)

            self.assertEqual(snapshot.inventory.manager, ResolverManager.SYSTEMD_RESOLVED)
            self.assertIn(["resolvectl", "dns", "tun0", "127.0.0.1"], runner.commands)
            self.assertIn(["resolvectl", "domain", "tun0", "~."], runner.commands)
            self.assertIn(["resolvectl", "revert", "tun0"], runner.commands)
            self.assertEqual(resolv_conf.read_text(encoding="utf-8"), "nameserver 127.0.0.53\n")

    def test_systemd_resolved_restore_does_not_touch_resolv_conf_symlink(self) -> None:
        # apply_local_dns for systemd-resolved only ever calls resolvectl -
        # it never touches /etc/resolv.conf. Real /etc/resolv.conf is a
        # symlink to systemd-resolved's own stub file
        # (/run/systemd/resolve/stub-resolv.conf), owned by root; a real
        # field run showed restore attempting to replace that symlink
        # anyway, failing with "Permission denied" for a normal caller even
        # though the actual resolvectl revert had already succeeded.
        with tempfile.TemporaryDirectory() as tmp:
            stub = Path(tmp) / "stub-resolv.conf"
            stub.write_text("nameserver 127.0.0.53\n", encoding="utf-8")
            resolv_conf = Path(tmp) / "resolv.conf"
            resolv_conf.symlink_to(stub)
            runner = FakeRunner(active_services={"systemd-resolved.service"})
            manager = SystemDNSStateManager(resolv_conf_path=resolv_conf, runner=runner)

            snapshot = manager.apply_local_dns(
                LocalDNSEntryPoint(address="127.0.0.1", systemd_link="tun0")
            )
            with patch("dns.state_manager._replace_symlink") as replace_symlink:
                manager.restore_state(snapshot)
            replace_symlink.assert_not_called()
            self.assertIn(["resolvectl", "revert", "tun0"], runner.commands)
            self.assertEqual(resolv_conf.resolve(), stub.resolve())

    def test_systemd_resolved_restore_skips_revert_but_flushes_when_link_is_gone(self) -> None:
        # Field bug: a profile can connect in proxy-only capture mode (no
        # TUN device), so "dns apply --systemd-link wdvpn-tun0" saves a
        # snapshot naming a link that was never actually brought up. If
        # restore always calls "resolvectl revert <link>" unconditionally,
        # it fails with "No such device" forever afterward - every later
        # "dns reset" against that same stale snapshot keeps failing the
        # same way, since the link never comes back on its own. Restoring
        # against a link that is gone should be a clean no-op instead: the
        # systemd-resolved config that link would have carried is already
        # gone with the interface itself.  A cache flush still matters after a
        # boot transition because stale FakeIP answers can outlive the link.
        with tempfile.TemporaryDirectory() as tmp:
            resolv_conf = Path(tmp) / "resolv.conf"
            resolv_conf.write_text("nameserver 127.0.0.53\n", encoding="utf-8")
            runner = FakeRunner(
                active_services={"systemd-resolved.service"},
                fail_on=("ip -o link show tun0",),
            )
            manager = SystemDNSStateManager(resolv_conf_path=resolv_conf, runner=runner)
            snapshot = manager.save_state(systemd_link="tun0")

            manager.restore_state(snapshot)

            self.assertIn(["ip", "-o", "link", "show", "tun0"], runner.commands)
            self.assertNotIn(["resolvectl", "revert", "tun0"], runner.commands)
            self.assertIn(["resolvectl", "flush-caches"], runner.commands)

    def test_apply_local_dns_failure_rolls_back_cleanly_when_link_is_gone(self) -> None:
        # Companion bug: when the apply itself fails because the named link
        # doesn't exist, apply_local_dns's own rollback (restore_state) used
        # to attempt the identical "resolvectl revert <link>" call, which
        # failed the same way and masked the original, more useful error
        # ("failed to apply local DNS entry point: ...") with a bare,
        # unwrapped "No such device" from the rollback attempt instead.
        with tempfile.TemporaryDirectory() as tmp:
            resolv_conf = Path(tmp) / "resolv.conf"
            resolv_conf.write_text("nameserver 127.0.0.53\n", encoding="utf-8")
            runner = FakeRunner(
                active_services={"systemd-resolved.service"},
                fail_on=("resolvectl dns", "ip -o link show tun0"),
            )
            manager = SystemDNSStateManager(resolv_conf_path=resolv_conf, runner=runner)

            with self.assertRaises(DNSStateError) as ctx:
                manager.apply_local_dns(
                    LocalDNSEntryPoint(address="127.0.0.1", systemd_link="tun0")
                )

            message = str(ctx.exception)
            self.assertIn("failed to apply local DNS entry point", message)
            self.assertNotIn(["resolvectl", "revert", "tun0"], runner.commands)

    def test_network_manager_apply_and_restore_connection_dns(self) -> None:
        with tempfile.TemporaryDirectory() as tmp:
            resolv_conf = Path(tmp) / "resolv.conf"
            resolv_conf.write_text(
                "# Generated by NetworkManager\nnameserver 192.0.2.1\n",
                encoding="utf-8",
            )
            runner = FakeRunner(
                active_services={"NetworkManager.service"},
                active_connections=("Home WiFi",),
                connection_values={
                    "Home WiFi": (
                        "192.0.2.1",
                        "no",
                        "lan",
                        "2001:db8::53",
                        "no",
                        "lan6",
                    )
                },
            )
            manager = SystemDNSStateManager(resolv_conf_path=resolv_conf, runner=runner)

            snapshot = manager.apply_local_dns(LocalDNSEntryPoint(address="127.0.0.1"))
            manager.restore_state(snapshot)

            self.assertEqual(snapshot.inventory.manager, ResolverManager.NETWORK_MANAGER)
            self.assertIn(
                [
                    "nmcli",
                    "con",
                    "mod",
                    "Home WiFi",
                    "ipv4.ignore-auto-dns",
                    "yes",
                    "ipv4.dns",
                    "127.0.0.1",
                    "ipv6.ignore-auto-dns",
                    "yes",
                    "ipv6.dns",
                    "",
                ],
                runner.commands,
            )
            self.assertIn(
                [
                    "nmcli",
                    "con",
                    "mod",
                    "Home WiFi",
                    "ipv4.ignore-auto-dns",
                    "no",
                    "ipv4.dns",
                    "192.0.2.1",
                    "ipv4.dns-search",
                    "lan",
                    "ipv6.ignore-auto-dns",
                    "no",
                    "ipv6.dns",
                    "2001:db8::53",
                    "ipv6.dns-search",
                    "lan6",
                ],
                runner.commands,
            )

    def test_network_manager_restore_with_empty_ipv4_dns_is_not_corrupted(self) -> None:
        # Rocky Linux 9 certification field bug (Task 23.6.5b): a plain DHCP
        # connection with no manual DNS override - the ordinary case, not an
        # edge case - has an empty ipv4.dns. The connection-state capture
        # used to issue one combined `nmcli -g
        # ipv4.dns,ipv4.ignore-auto-dns,...` call and split the result on
        # the shared runner's stripped blob; stripping ate the leading blank
        # line for the empty first field and shifted every value after it by
        # one position, so ipv4.ignore-auto-dns's "no"/"yes" landed in
        # ipv4_dns instead. Restore then fed that straight to `nmcli con mod
        # ... ipv4.dns no`, which nmcli correctly rejects as an invalid DNS
        # address, leaving DNS unrestored. Now each property is queried
        # (and stripped) independently, so an empty field can never shift
        # its neighbors.
        with tempfile.TemporaryDirectory() as tmp:
            resolv_conf = Path(tmp) / "resolv.conf"
            resolv_conf.write_text(
                "# Generated by NetworkManager\nnameserver 192.168.0.1\n",
                encoding="utf-8",
            )
            runner = FakeRunner(
                active_services={"NetworkManager.service"},
                active_connections=("enp0s3",),
                connection_values={
                    "enp0s3": ("", "no", "", "", "yes", ""),
                },
            )
            manager = SystemDNSStateManager(resolv_conf_path=resolv_conf, runner=runner)

            snapshot = manager.apply_local_dns(LocalDNSEntryPoint(address="127.0.0.1"))
            saved = snapshot.network_manager_connections[0]
            self.assertEqual(saved.ipv4_dns, "")
            self.assertEqual(saved.ipv4_ignore_auto_dns, "no")
            self.assertEqual(saved.ipv6_dns, "")
            self.assertEqual(saved.ipv6_ignore_auto_dns, "yes")

            manager.restore_state(snapshot)
            self.assertIn(
                [
                    "nmcli",
                    "con",
                    "mod",
                    "enp0s3",
                    "ipv4.ignore-auto-dns",
                    "no",
                    "ipv4.dns",
                    "",
                    "ipv4.dns-search",
                    "",
                    "ipv6.ignore-auto-dns",
                    "yes",
                    "ipv6.dns",
                    "",
                    "ipv6.dns-search",
                    "",
                ],
                runner.commands,
            )

    def test_network_manager_loopback_only_falls_back_to_resolv_conf(self) -> None:
        # Debian certification VM regression: NetworkManager was installed and
        # active, but the only NM connection was loopback while the real bridge
        # interface was managed by ifupdown/dhcpcd. Selecting NetworkManager in
        # that state made dns reset try to restore ipv4.dns on "lo", which NM
        # rejects and leaves /etc/resolv.conf pinned to 127.0.0.1.
        with tempfile.TemporaryDirectory() as tmp:
            resolv_conf = Path(tmp) / "resolv.conf"
            original = "nameserver 192.0.2.1\n"
            resolv_conf.write_text(original, encoding="utf-8")
            runner = FakeRunner(
                active_services={"NetworkManager.service"},
                active_connections=("lo:loopback:lo",),
            )
            manager = SystemDNSStateManager(resolv_conf_path=resolv_conf, runner=runner)

            snapshot = manager.apply_local_dns(LocalDNSEntryPoint(address="127.0.0.1"))
            manager.restore_state(snapshot)

            self.assertEqual(snapshot.inventory.manager, ResolverManager.RESOLV_CONF)
            self.assertEqual(resolv_conf.read_text(encoding="utf-8"), original)
            self.assertNotIn(
                [
                    "nmcli",
                    "con",
                    "mod",
                    "lo",
                    "ipv4.ignore-auto-dns",
                    "no",
                    "ipv4.dns",
                    "",
                    "ipv4.dns-search",
                    "",
                    "ipv6.ignore-auto-dns",
                    "no",
                    "ipv6.dns",
                    "",
                    "ipv6.dns-search",
                    "",
                ],
                runner.commands,
            )

    def test_network_manager_active_with_dhcpcd_resolv_conf_uses_resolv_conf(self) -> None:
        # Companion Debian certification regression: while WatchdogVPN was
        # connected, an NM-visible non-loopback runtime connection existed,
        # but the system resolver file was still generated by dhcpcd for the
        # bridge interface. DNS apply reported success through NM while
        # leaving /etc/resolv.conf unchanged.
        with tempfile.TemporaryDirectory() as tmp:
            resolv_conf = Path(tmp) / "resolv.conf"
            original = "# Generated by dhcpcd from eth0.dhcp\nnameserver 192.0.2.1\n"
            resolv_conf.write_text(original, encoding="utf-8")
            runner = FakeRunner(
                active_services={"NetworkManager.service"},
                active_connections=("watchdogvpn:wireguard:wdvpn-tun0",),
            )
            manager = SystemDNSStateManager(resolv_conf_path=resolv_conf, runner=runner)

            snapshot = manager.apply_local_dns(LocalDNSEntryPoint(address="127.0.0.1"))

            self.assertEqual(snapshot.inventory.manager, ResolverManager.RESOLV_CONF)
            self.assertEqual(resolv_conf.read_text(encoding="utf-8"), "nameserver 127.0.0.1\n")
            manager.restore_state(snapshot)
            self.assertEqual(resolv_conf.read_text(encoding="utf-8"), original)

    def test_classic_resolv_conf_apply_and_restore(self) -> None:
        with tempfile.TemporaryDirectory() as tmp:
            resolv_conf = Path(tmp) / "resolv.conf"
            original = "search lan\nnameserver 203.0.113.53\n"
            resolv_conf.write_text(original, encoding="utf-8")
            manager = SystemDNSStateManager(
                resolv_conf_path=resolv_conf,
                runner=FakeRunner(),
            )

            snapshot = manager.apply_local_dns(LocalDNSEntryPoint(address="127.0.0.1"))

            self.assertEqual(snapshot.inventory.manager, ResolverManager.RESOLV_CONF)
            self.assertEqual(resolv_conf.read_text(encoding="utf-8"), "nameserver 127.0.0.1\n")
            manager.restore_state(snapshot)
            self.assertEqual(resolv_conf.read_text(encoding="utf-8"), original)

    def test_resolv_conf_symlink_to_static_target_restores_content(self) -> None:
        # openSUSE certification field bug: /etc/resolv.conf there is a
        # symlink to /run/netconfig/resolv.conf, a plain file netconfig
        # writes once and never regenerates on its own (unlike
        # systemd-resolved's or NetworkManager's self-managed stubs).
        # apply_local_dns's write_text follows the symlink and clobbers that
        # target's content; restoring only the symlink (pointing right back
        # at the same, still-clobbered file) left every DNS lookup broken
        # the moment WatchdogVPN's local resolver went away on disconnect.
        with tempfile.TemporaryDirectory() as tmp:
            root = Path(tmp)
            target = root / "netconfig-resolv.conf"
            original = "nameserver 192.168.0.1\n"
            target.write_text(original, encoding="utf-8")
            resolv_conf = root / "resolv.conf"
            resolv_conf.symlink_to(target)
            manager = SystemDNSStateManager(
                resolv_conf_path=resolv_conf,
                runner=FakeRunner(),
            )

            snapshot = manager.apply_local_dns(LocalDNSEntryPoint(address="127.0.0.1"))

            self.assertEqual(snapshot.inventory.manager, ResolverManager.RESOLV_CONF)
            self.assertEqual(target.read_text(encoding="utf-8"), "nameserver 127.0.0.1\n")
            manager.restore_state(snapshot)
            self.assertEqual(resolv_conf.resolve(), target.resolve())
            self.assertEqual(target.read_text(encoding="utf-8"), original)

    def test_unknown_manager_uses_dns_rescue_fallback(self) -> None:
        with tempfile.TemporaryDirectory() as tmp:
            runner = FakeRunner()
            manager = SystemDNSStateManager(
                resolv_conf_path=Path(tmp) / "missing.conf",
                runner=runner,
                rescue_command=Path("/usr/local/bin/vpn_dns_rescue"),
            )
            snapshot = manager.save_state()

            manager.restore_state(snapshot)

            self.assertEqual(snapshot.inventory.manager, ResolverManager.UNKNOWN)
            self.assertIn(
                ["/usr/local/bin/vpn_dns_rescue", "auto", "--no-reconnect"],
                runner.commands,
            )

    def test_failed_network_manager_apply_restores_saved_state(self) -> None:
        with tempfile.TemporaryDirectory() as tmp:
            resolv_conf = Path(tmp) / "resolv.conf"
            resolv_conf.write_text(
                "# Generated by NetworkManager\nnameserver 192.0.2.1\n",
                encoding="utf-8",
            )
            runner = FakeRunner(
                active_services={"NetworkManager.service"},
                active_connections=("Home WiFi",),
                connection_values={
                    "Home WiFi": ("192.0.2.1", "no", "", "", "no", "")
                },
                fail_on=("127.0.0.1",),
            )
            manager = SystemDNSStateManager(resolv_conf_path=resolv_conf, runner=runner)

            with self.assertRaises(DNSStateError):
                manager.apply_local_dns(LocalDNSEntryPoint(address="127.0.0.1"))

            restore_command = [
                "nmcli",
                "con",
                "mod",
                "Home WiFi",
                "ipv4.ignore-auto-dns",
                "no",
                "ipv4.dns",
                "192.0.2.1",
                "ipv4.dns-search",
                "",
                "ipv6.ignore-auto-dns",
                "no",
                "ipv6.dns",
                "",
                "ipv6.dns-search",
                "",
            ]
            self.assertIn(restore_command, runner.commands)

    def test_default_runner_does_not_raise_for_inactive_systemd_service(self) -> None:
        with patch("subprocess.run") as run:
            run.return_value = CompletedProcess(
                args=["systemctl", "is-active", "NetworkManager.service"],
                returncode=3,
                stdout="inactive\n",
                stderr="",
            )

            result = _run_command(["systemctl", "is-active", "NetworkManager.service"])

            self.assertEqual(result, "inactive")


class DNSSnapshotHelperTests(unittest.TestCase):
    def test_default_snapshot_path_respects_env_override(self) -> None:
        with patch.dict(
            "os.environ",
            {"WATCHDOGVPN_DNS_SNAPSHOT_FILE": "/tmp/custom-dns-state.json"},
        ):
            self.assertEqual(default_snapshot_path(), Path("/tmp/custom-dns-state.json"))

    def test_load_snapshot_returns_none_when_missing(self) -> None:
        with tempfile.TemporaryDirectory() as tmp:
            missing = Path(tmp) / "missing.json"
            self.assertIsNone(load_snapshot(missing))

    def test_load_snapshot_round_trips_a_saved_snapshot(self) -> None:
        with tempfile.TemporaryDirectory() as tmp:
            resolv_conf = Path(tmp) / "resolv.conf"
            resolv_conf.write_text("nameserver 127.0.0.53\n", encoding="utf-8")
            runner = FakeRunner(active_services={"systemd-resolved.service"})
            manager = SystemDNSStateManager(resolv_conf_path=resolv_conf, runner=runner)
            snapshot = manager.save_state(systemd_link="tun0")
            snapshot_path = Path(tmp) / "dns-state.json"
            snapshot_path.write_text(
                json.dumps(snapshot.to_dict()),
                encoding="utf-8",
            )

            loaded = load_snapshot(snapshot_path)

            self.assertIsNotNone(loaded)
            self.assertEqual(loaded.inventory.manager, ResolverManager.SYSTEMD_RESOLVED)
            self.assertEqual(loaded.systemd_link, "tun0")

    def test_load_snapshot_raises_on_invalid_json_shape(self) -> None:
        with tempfile.TemporaryDirectory() as tmp:
            snapshot_path = Path(tmp) / "dns-state.json"
            snapshot_path.write_text("[]", encoding="utf-8")

            with self.assertRaises(DNSStateError):
                load_snapshot(snapshot_path)


if __name__ == "__main__":
    unittest.main()
