"""WatchdogVPN compatibility domain (Phase 23.7.5).

This package holds the compatibility contract's pure domain model. The manifest,
detection, provisioning and their integrations are added by later frozen tasks.
"""

from __future__ import annotations

from compat.support_model import (
    CoreCapabilityStatus,
    DomainError,
    FreshnessState,
    HostReadiness,
    ProtocolReadiness,
    ProtocolRuntimeStatus,
    ReleaseModel,
    RollingFacts,
    StableReleaseFacts,
    SupportClassification,
    check_rolling_invariants,
    check_stable_invariants,
    classify_host_readiness,
    classify_protocol_readiness,
    classify_support,
    classify_support_rolling,
    classify_support_stable,
    evaluate_freshness,
    parse,
    to_value,
)
from compat.detection import (
    CapabilityResult,
    CommandResult,
    DetectionError,
    DistroFacts,
    EvaluationReport,
    FakeCommandRunner,
    OsReleaseData,
    ProbeEnvironment,
    SafeCommandRunner,
    detect_current,
    distro_facts_from_os_release,
    evaluate,
    normalize_id,
    parse_os_release_text,
    probe_core_capabilities,
    probe_protocol_capabilities,
    read_os_release,
)
from compat.dependency_resolution import (
    AvailabilityObservation,
    AvailabilityProvider,
    AvailabilityStatus,
    CandidateRejection,
    DependencyRequirement,
    DependencyResolutionError,
    MethodCandidate,
    ResolutionDecision,
    ResolutionReport,
    ResolutionStatus,
    StaticAvailabilityProvider,
    explain_resolution,
    resolve_all,
    resolve_dependency,
)

__all__ = [
    "CoreCapabilityStatus",
    "DomainError",
    "FreshnessState",
    "HostReadiness",
    "ProtocolReadiness",
    "ProtocolRuntimeStatus",
    "ReleaseModel",
    "RollingFacts",
    "StableReleaseFacts",
    "SupportClassification",
    "check_rolling_invariants",
    "check_stable_invariants",
    "classify_host_readiness",
    "classify_protocol_readiness",
    "classify_support",
    "classify_support_rolling",
    "classify_support_stable",
    "evaluate_freshness",
    "parse",
    "to_value",
    "CapabilityResult",
    "CommandResult",
    "DetectionError",
    "DistroFacts",
    "EvaluationReport",
    "FakeCommandRunner",
    "OsReleaseData",
    "ProbeEnvironment",
    "SafeCommandRunner",
    "detect_current",
    "distro_facts_from_os_release",
    "evaluate",
    "normalize_id",
    "parse_os_release_text",
    "probe_core_capabilities",
    "probe_protocol_capabilities",
    "read_os_release",
    "AvailabilityObservation",
    "AvailabilityProvider",
    "AvailabilityStatus",
    "CandidateRejection",
    "DependencyRequirement",
    "DependencyResolutionError",
    "MethodCandidate",
    "ResolutionDecision",
    "ResolutionReport",
    "ResolutionStatus",
    "StaticAvailabilityProvider",
    "explain_resolution",
    "resolve_all",
    "resolve_dependency",
]
