#!/usr/bin/env python3
"""Internal dependency-method resolver tool for Phase 23.7.5.5.

This is not a public WatchdogVPN CLI and does not execute selected methods.
"""

from __future__ import annotations

import argparse
import sys
from datetime import datetime, timezone
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from compat import dependency_resolution as resolver
from compat import detection
from tools import compat_read


EXIT_USAGE = 1
EXIT_RESOLUTION_ERROR = 2


def _load_manifest(path: str | None):
    manifest_path = Path(path) if path else Path(compat_read.DEFAULT_MANIFEST_PATH)
    manifest = compat_read.load_manifest_file(manifest_path, product_path=path is None)
    compat_read.validate_manifest(manifest)
    return manifest


def _load_os_release(args) -> detection.OsReleaseData:
    if args.os_release:
        return detection.read_os_release(
            etc_path=Path(args.os_release),
            usr_path=Path(args.usr_os_release) if args.usr_os_release else Path(args.os_release),
        )
    return detection.read_os_release(
        usr_path=Path(args.usr_os_release) if args.usr_os_release else Path("/usr/lib/os-release"),
    )


def _fixture_env() -> detection.ProbeEnvironment:
    ok = detection.CommandResult(("probe",), "ok", 0, "ok\n", "")
    return detection.ProbeEnvironment(
        runner=detection.FakeCommandRunner(
            {
                ("apt-get", "--version"): ok,
                ("dnf", "--version"): ok,
                ("zypper", "--version"): ok,
                ("pacman", "--version"): ok,
                ("sudo", "-V"): ok,
                ("pkaction", "--version"): ok,
                ("nmcli", "-t", "-f", "RUNNING", "general"): detection.CommandResult(
                    ("nmcli", "-t", "-f", "RUNNING", "general"), "ok", 0, "running\n", ""
                ),
                ("nft", "--version"): ok,
                ("ip", "rule", "show"): ok,
                ("sing-box", "version"): ok,
                ("openvpn", "--version"): ok,
                ("ck-client", "-v"): ok,
                ("awg", "--version"): detection.CommandResult(("awg", "--version"), "command_missing"),
                ("amneziawg-go", "--version"): detection.CommandResult(("amneziawg-go", "--version"), "command_missing"),
                ("getenforce",): detection.CommandResult(("getenforce",), "ok", 0, "Disabled\n", ""),
                ("firewall-cmd", "--state"): detection.CommandResult(("firewall-cmd", "--state"), "command_missing", reason="fixture missing"),
            }
        ),
        files={
            "/proc/1/comm": "systemd\n",
            "/etc/resolv.conf": "# generated by systemd-resolved\n",
            "/proc/modules": "",
            "/sys/module/apparmor/parameters/enabled": "Y\n",
        },
        existing_paths={"/dev/net/tun"},
        machine_architecture="x86_64",
        kernel_release="6.8.0-fixture",
        python_version=(3, 11, 0),
        allow_host_fallback=False,
    )


def _context(args):
    manifest = _load_manifest(args.manifest)
    os_release = _load_os_release(args)
    env = _fixture_env() if args.fixture_host else detection.ProbeEnvironment()
    facts = detection.distro_facts_from_os_release(
        os_release,
        manifest,
        kernel_release=env.kernel_release,
        machine_architecture=env.machine_architecture,
    )
    core = list(detection.probe_core_capabilities(manifest, facts, env))
    protocol = list(detection.probe_protocol_capabilities(manifest, env))
    missing = set(args.missing_capability or ())
    for index, item in enumerate(core):
        if item.capability_id in missing:
            core[index] = detection.CapabilityResult(
                item.capability_id,
                "absent",
                "provisionable",
                item.evidence,
                item.probe_method,
                "forced absent by explicit resolver fixture option",
                item.error_kind,
            )
    for index, item in enumerate(protocol):
        if item.capability_id in missing:
            protocol[index] = detection.CapabilityResult(
                item.capability_id,
                "absent",
                "provisionable",
                item.evidence,
                item.probe_method,
                "forced absent by explicit resolver fixture option",
                item.error_kind,
            )
    now = datetime.now(timezone.utc).replace(tzinfo=None)
    report = detection.evaluate(manifest, facts, core, protocol, now=now)
    capabilities = tuple(report.core_capabilities) + tuple(report.protocol_capabilities)
    return manifest, facts, report.support_classification, capabilities


def _provider(args) -> resolver.AvailabilityProvider:
    if not args.fixture_host:
        return resolver.AvailabilityProvider()
    if args.availability == "available":
        return resolver.StaticAvailabilityProvider.all_available()
    return resolver.StaticAvailabilityProvider()


def _provider_metadata(provider: resolver.AvailabilityProvider) -> dict:
    return {
        "type": getattr(provider, "provider_type", provider.__class__.__name__),
        "authoritative": bool(getattr(provider, "authoritative", False)),
    }


def _print(value) -> None:
    print(detection.stable_json(detection.to_jsonable(value)))


def cmd_dependency(args) -> int:
    manifest, facts, support, capabilities = _context(args)
    provider = _provider(args)
    decision = resolver.resolve_dependency(
        manifest,
        facts,
        support,
        capabilities,
        args.dependency_id,
        availability=provider,
    )
    _print({"provider": _provider_metadata(provider), "decision": decision})
    return 0


def cmd_all(args) -> int:
    manifest, facts, support, capabilities = _context(args)
    provider = _provider(args)
    _print({"provider": _provider_metadata(provider), "report": resolver.resolve_all(manifest, facts, support, capabilities, availability=provider)})
    return 0


def cmd_explain(args) -> int:
    manifest, facts, support, capabilities = _context(args)
    provider = _provider(args)
    decision = resolver.resolve_dependency(
        manifest,
        facts,
        support,
        capabilities,
        args.dependency_id,
        availability=provider,
    )
    _print({"provider": _provider_metadata(provider), "explanation": resolver.explain_resolution(decision)})
    return 0


def cmd_matrix(args) -> int:
    manifest, facts, support, capabilities = _context(args)
    provider = _provider(args)
    report = resolver.resolve_all(manifest, facts, support, capabilities, availability=provider)
    payload = {
        "provider": _provider_metadata(provider),
        "target": {
            "distribution": report.resolved_distribution,
            "release": report.resolved_release,
            "release_model": report.release_model,
            "support_classification": report.support_classification,
        },
        "decisions": {
            decision.dependency_id: {
                "status": decision.resolution_status,
                "selected_method_id": decision.selected_method_id,
                "execution_ready": decision.execution_ready,
            }
            for decision in report.decisions
        },
    }
    _print(payload)
    return 0


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--manifest", help="manifest path; defaults to product manifest")
    parser.add_argument("--os-release", help="explicit /etc/os-release fixture path")
    parser.add_argument("--usr-os-release", help="explicit /usr/lib/os-release fallback fixture path")
    parser.add_argument("--fixture-host", action="store_true", help="use deterministic read-only fixture probes")
    parser.add_argument("--missing-capability", action="append", help="force a capability result absent in fixture mode")
    parser.add_argument("--availability", choices=("available", "unknown"), default="unknown")
    sub = parser.add_subparsers(dest="command", required=True)
    dependency = sub.add_parser("dependency")
    dependency.add_argument("dependency_id")
    dependency.set_defaults(func=cmd_dependency)
    sub.add_parser("all").set_defaults(func=cmd_all)
    explain = sub.add_parser("explain")
    explain.add_argument("dependency_id")
    explain.set_defaults(func=cmd_explain)
    sub.add_parser("matrix").set_defaults(func=cmd_matrix)
    return parser


def main(argv=None) -> int:
    parser = build_parser()
    args = parser.parse_args(argv)
    if not args.fixture_host and args.availability == "available":
        print("error: --availability available requires --fixture-host", file=sys.stderr)
        return EXIT_USAGE
    if not args.fixture_host and args.missing_capability:
        print("error: --missing-capability requires --fixture-host", file=sys.stderr)
        return EXIT_USAGE
    try:
        return args.func(args)
    except (compat_read.ManifestError, detection.DetectionError, resolver.DependencyResolutionError, ValueError) as exc:
        print("error: %s" % exc, file=sys.stderr)
        return EXIT_RESOLUTION_ERROR


if __name__ == "__main__":
    raise SystemExit(main())
