#!/usr/bin/env python3
"""Internal read-only compatibility probe tool for Phase 23.7.5.4."""

from __future__ import annotations

import argparse
import sys
from datetime import datetime, timezone
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from compat import detection
from tools import compat_read


EXIT_USAGE = 1
EXIT_DETECTION_ERROR = 2


def _load_manifest(path: str | None):
    manifest_path = Path(path) if path else Path(compat_read.DEFAULT_MANIFEST_PATH)
    manifest = compat_read.load_manifest_file(manifest_path, product_path=path is None)
    compat_read.validate_manifest(manifest)
    return manifest


def _load_os_release(args) -> detection.OsReleaseData:
    if args.os_release:
        return detection.read_os_release(
            etc_path=Path(args.os_release),
            usr_path=Path(args.usr_os_release) if args.usr_os_release else Path(args.os_release),
        )
    return detection.read_os_release(
        usr_path=Path(args.usr_os_release) if args.usr_os_release else Path("/usr/lib/os-release"),
    )


def _fixture_env() -> detection.ProbeEnvironment:
    ok = detection.CommandResult(("probe",), "ok", 0, "ok\n", "")
    return detection.ProbeEnvironment(
        runner=detection.FakeCommandRunner(
            {
                ("apt-get", "--version"): ok,
                ("dnf", "--version"): ok,
                ("zypper", "--version"): ok,
                ("pacman", "--version"): ok,
                ("sudo", "-V"): ok,
                ("pkaction", "--version"): ok,
                ("nmcli", "-t", "-f", "RUNNING", "general"): detection.CommandResult(
                    ("nmcli", "-t", "-f", "RUNNING", "general"), "ok", 0, "running\n", ""
                ),
                ("nft", "--version"): ok,
                ("ip", "rule", "show"): ok,
                ("sing-box", "version"): ok,
                ("openvpn", "--version"): ok,
                ("ck-client", "-v"): ok,
                ("awg", "--version"): ok,
                ("amneziawg-go", "--version"): detection.CommandResult(
                    ("amneziawg-go", "--version"), "command_missing"
                ),
                ("getenforce",): detection.CommandResult(("getenforce",), "ok", 0, "Disabled\n", ""),
                ("python3", "-c", "import sys; print('%d.%d.%d' % sys.version_info[:3])"): detection.CommandResult(("python3", "-c", "import sys; print('%d.%d.%d' % sys.version_info[:3])"), "ok", 0, "3.11.0\n", ""),
                ("python3", "-c", "import cryptography; print(cryptography.__version__)"): detection.CommandResult(("python3", "-c", "import cryptography; print(cryptography.__version__)"), "ok", 0, "42.0.0\n", ""),
                ("python3.11", "-c", "import sys; print('%d.%d.%d' % sys.version_info[:3])"): detection.CommandResult(("python3.11", "-c", "import sys; print('%d.%d.%d' % sys.version_info[:3])"), "ok", 0, "3.11.0\n", ""),
                ("python3.11", "-c", "import cryptography; print(cryptography.__version__)"): detection.CommandResult(("python3.11", "-c", "import cryptography; print(cryptography.__version__)"), "ok", 0, "42.0.0\n", ""),
                ("python", "-c", "import sys; print('%d.%d.%d' % sys.version_info[:3])"): detection.CommandResult(("python", "-c", "import sys; print('%d.%d.%d' % sys.version_info[:3])"), "ok", 0, "3.11.0\n", ""),
                ("python", "-c", "import cryptography; print(cryptography.__version__)"): detection.CommandResult(("python", "-c", "import cryptography; print(cryptography.__version__)"), "ok", 0, "42.0.0\n", ""),
            }
        ),
        files={
            "/proc/1/comm": "systemd\n",
            "/etc/resolv.conf": "# generated by systemd-resolved\n",
            "/proc/modules": "",
            "/sys/module/apparmor/parameters/enabled": "Y\n",
        },
        existing_paths={"/dev/net/tun"},
        machine_architecture="x86_64",
        kernel_release="6.8.0-fixture",
        python_version=(3, 11, 0),
        allow_host_fallback=False,
    )


def _facts(manifest, args):
    os_release = _load_os_release(args)
    env = _fixture_env() if args.fixture_host else detection.ProbeEnvironment()
    return detection.distro_facts_from_os_release(
        os_release,
        manifest,
        kernel_release=env.kernel_release,
        machine_architecture=env.machine_architecture,
    ), env


def _print(value) -> None:
    print(detection.stable_json(detection.to_jsonable(value)))


def cmd_detect(args) -> int:
    manifest = _load_manifest(args.manifest)
    facts, _env = _facts(manifest, args)
    _print(facts)
    return 0


def cmd_capabilities(args) -> int:
    manifest = _load_manifest(args.manifest)
    facts, env = _facts(manifest, args)
    payload = {
        "core": detection.probe_core_capabilities(manifest, facts, env),
        "protocol": detection.probe_protocol_capabilities(manifest, env),
    }
    _print(payload)
    return 0


def cmd_evaluate(args) -> int:
    manifest = _load_manifest(args.manifest)
    facts, env = _facts(manifest, args)
    core = detection.probe_core_capabilities(manifest, facts, env)
    protocol = detection.probe_protocol_capabilities(manifest, env)
    now = datetime.now(timezone.utc).replace(tzinfo=None)
    _print(detection.evaluate(manifest, facts, core, protocol, now=now))
    return 0


def cmd_report(args) -> int:
    return cmd_evaluate(args)


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--manifest", help="manifest path; defaults to product manifest")
    parser.add_argument("--os-release", help="explicit /etc/os-release fixture path")
    parser.add_argument("--usr-os-release", help="explicit /usr/lib/os-release fallback fixture path")
    parser.add_argument(
        "--fixture-host",
        action="store_true",
        help="use deterministic read-only fixture probes instead of host commands",
    )
    sub = parser.add_subparsers(dest="command", required=True)
    sub.add_parser("detect").set_defaults(func=cmd_detect)
    sub.add_parser("capabilities").set_defaults(func=cmd_capabilities)
    sub.add_parser("evaluate").set_defaults(func=cmd_evaluate)
    sub.add_parser("report").set_defaults(func=cmd_report)
    return parser


def main(argv=None) -> int:
    parser = build_parser()
    args = parser.parse_args(argv)
    try:
        return args.func(args)
    except (compat_read.ManifestError, detection.DetectionError, ValueError) as exc:
        print("error: %s" % exc, file=sys.stderr)
        return EXIT_DETECTION_ERROR


if __name__ == "__main__":
    raise SystemExit(main())
